# Generated by Django 6.0.6 on 2026-06-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('no_show', 'No asistió')], default='pending', max_length=20),
        ),
    ]
