# Generated by Django 6.0.6 on 2026-06-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='appointment_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
