# Generated by Django 6.0.6 on 2026-06-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_specialty'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps_name', models.CharField(max_length=100, unique=True)),
                ('appointment_limit', models.PositiveIntegerField(default=0)),
                ('budget_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
