# Generated by Django 6.0.6 on 2026-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_epsconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workday_start', models.TimeField(default='08:00')),
                ('workday_end', models.TimeField(default='17:00')),
                ('max_days_in_advance', models.PositiveIntegerField(default=30)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('holidays_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
